# Ignore our `vendor` folder from Bundler
# https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902
exclude: [vendor]

# Default permalink format
permalink: /:year/:month/:day/:title

# Build settings (updated 2020-03-03 BP)
plugins:
  - jekyll-feed
  - jekyll-paginate

# Other stuff
markdown: kramdown
highlighter: rouge
paginate: 5
future: true

title: LDC Via
tagline: "Occasional witterings&hellip;"
author:
  name: LDC Via
  email: support@ldcvia.com
  github: ldcvia

production_url: https://blog.ldcvia.com

JB:
  version: 0.3.0
  archive_path: /archive.html
  categories_path: /categories.html
  tags_path: /tags.html
  atom_path: /atom.xml
  rss_path: /rss.xml

BASE_PATH: false
ASSET_PATH: /assets/themes/ldcvia/
